export const SET_SEARCHED_STATIONS = 'SET_SEARCHED_STATIONS';
export const SET_STATIONS = 'SET_STATIONS';

// Navigation
export const NAVIGATION_FORWARD = 'NAVIGATION_FORWARD';
export const NAVIGATION_BACK = 'NAVIGATION_BACK';